Reduces the stack trace size of flicker exceptions
We use a wrapping exception to better work with the ATH clustering algorithms, however this was printing the exception callstack 2x. Now it prints as follows:

```
com.android.server.wm.flicker.assertions.FlickerAssertionError: Flicker assertion error

Where? 2023-01-05T11:28:21.166405670 (1672918101166405670ns)
What?
	Region to test  : SkRegion((0,0,1280,720))
	Covered region  : SkRegion((560,0,1280,1280))
	Uncovered region: SkRegion((0,0,560,720)(560,720,1280,1280))

Facts:
	Region - Covered: SkRegion((560,0,1280,1280))
	SF State: Timestamp(elapsedNanos=0, systemUptimeNanos=3862408482465, unixNanos=1672918101166405670)ns
	Trace start: 2023-01-05T11:28:18.719221764 (1672918098719221764ns)
	Trace end: 2023-01-05T11:28:21.583088677 (1672918101583088677ns)
	Location: during transition

Trace file:	/sdcard/flicker/FAIL___SeamlessAppRotationTest_ROTATION_90_ROTATION_0_GESTURAL_NAV_BUSY_UI_THREAD.zip
Cause:
	Region to test  : SkRegion((0,0,1280,720))
Covered region  : SkRegion((560,0,1280,1280))
Uncovered region: SkRegion((0,0,560,720)(560,720,1280,1280))
	at com.android.server.wm.flicker.assertions.AssertionDataFactory$createTraceAssertion$closedAssertion$1.invoke(AssertionDataFactory.kt:45)
	at com.android.server.wm.flicker.assertions.AssertionDataFactory$createTraceAssertion$closedAssertion$1.invoke(AssertionDataFactory.kt:42)
	at com.android.server.wm.flicker.assertions.AssertionData.checkAssertion(AssertionData.kt:42)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.doRunAssertion(BaseAssertionRunner.kt:46)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.runAssertion(BaseAssertionRunner.kt:41)
	at com.android.server.wm.flicker.FlickerTest.doRunAssertion(FlickerTest.kt:253)
	at com.android.server.wm.flicker.FlickerTest.access$doRunAssertion(FlickerTest.kt:40)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:188)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:183)
	at com.android.server.wm.traces.parser.Extensions.withPerfettoTrace(Extensions.kt:127)
	at com.android.server.wm.flicker.FlickerTest.assertLayers(FlickerTest.kt:183)
	at com.android.server.wm.flicker.rotation.SeamlessAppRotationTest.appLayerRotates(SeamlessAppRotationTest.kt:153)

Full stacktrace:

	at com.android.server.wm.flicker.assertions.FlickerAssertionErrorBuilder.build(FlickerAssertionErrorBuilder.kt:49)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.doRunAssertion(BaseAssertionRunner.kt:55)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.runAssertion(BaseAssertionRunner.kt:41)
	at com.android.server.wm.flicker.FlickerTest.doRunAssertion(FlickerTest.kt:253)
	at com.android.server.wm.flicker.FlickerTest.access$doRunAssertion(FlickerTest.kt:40)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:188)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:183)
	at com.android.server.wm.traces.parser.Extensions.withPerfettoTrace(Extensions.kt:127)
	at com.android.server.wm.flicker.FlickerTest.assertLayers(FlickerTest.kt:183)
	at com.android.server.wm.flicker.rotation.SeamlessAppRotationTest.appLayerRotates(SeamlessAppRotationTest.kt:153)
	... 41 trimmed
Caused by: Region to test  : SkRegion((0,0,1280,720))
Covered region  : SkRegion((560,0,1280,1280))
Uncovered region: SkRegion((0,0,560,720)(560,720,1280,1280))
	at com.android.server.wm.flicker.assertions.AssertionDataFactory$createTraceAssertion$closedAssertion$1.invoke(AssertionDataFactory.kt:45)
	at com.android.server.wm.flicker.assertions.AssertionDataFactory$createTraceAssertion$closedAssertion$1.invoke(AssertionDataFactory.kt:42)
	at com.android.server.wm.flicker.assertions.AssertionData.checkAssertion(AssertionData.kt:42)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.doRunAssertion(BaseAssertionRunner.kt:46)
	at com.android.server.wm.flicker.assertions.BaseAssertionRunner.runAssertion(BaseAssertionRunner.kt:41)
	at com.android.server.wm.flicker.FlickerTest.doRunAssertion(FlickerTest.kt:253)
	at com.android.server.wm.flicker.FlickerTest.access$doRunAssertion(FlickerTest.kt:40)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:188)
	at com.android.server.wm.flicker.FlickerTest$assertLayers$1.invoke(FlickerTest.kt:183)
	at com.android.server.wm.traces.parser.Extensions.withPerfettoTrace(Extensions.kt:127)
	at com.android.server.wm.flicker.FlickerTest.assertLayers(FlickerTest.kt:183)
	at com.android.server.wm.flicker.rotation.SeamlessAppRotationTest.appLayerRotates(SeamlessAppRotationTest.kt:153)
```

Test: atest FlickerLibTest
Bug: 264354843
Change-Id: Iac6c82e64f6a4eb3dfe0c0d716eabee851ce85db