Swap assert arguments
While this swap does not impact whether a test passes or fails,
it changes the error message from something like:
 expected:<1> but was:<0>
to:
 expected:<0> but was:<1>

We expect no (0) errors, we don't expect 1 (or however many) errors
we get.

https://source.corp.google.com/android/external/junit/src/main/java/org/junit/Assert.java;rcl=HEAD;l=645
lists 'expected' as the first of the two value arguments.

Test: TreeHugger
Change-Id: Ic1c42d364ee04c265c3dd67c18f4745b37da5065